branches:
  only:
    - master

image:
- Ubuntu1804
# - Visual Studio 2015

configuration: Release

environment:
  # mg_artifact_name: cdd-v$(APPVEYOR_BUILD_VERSION).zip
  mg_artifact_name: cdd-v$(APPVEYOR_REPO_TAG_NAME).zip
  mg_appveyor_build_version_1a: appveyor_build_version
  mg_appveyor_build_version_1b: APPVEYOR_BUILD_VERSION
  # mg_appveyor_build_version_2a: {appveyor_build_version}
  # mg_appveyor_build_version_2b: {APPVEYOR_BUILD_VERSION}
  mg_appveyor_build_version_3a: '{appveyor_build_version}'
  mg_appveyor_build_version_3b: '{APPVEYOR_BUILD_VERSION}'
  mg_appveyor_build_version_4a: $(appveyor_build_version)
  # This works:
  mg_appveyor_build_version_4b: $(APPVEYOR_BUILD_VERSION)
  mg_appveyor_build_version_5a: '$(appveyor_build_version)'
  # This works:
  mg_appveyor_build_version_5b: '$(APPVEYOR_BUILD_VERSION)'

# build:
#   project: CMakeLists.txt

before_build:
  sh: |
    echo APPVEYOR_REPO_TAG_NAME: $APPVEYOR_REPO_TAG_NAME
    echo APPVEYOR_BUILD_VERSION: $APPVEYOR_BUILD_VERSION

build_script:
  - sh: |
      echo MG build part of build_script
      mkdir build
      cd build
      cmake --version
      cmake ..
      cmake --build .
      echo MG before_deploy part of build_script
      echo mg_appveyor_build_version_4b: $mg_appveyor_build_version_4b
      echo xx echo 1 mg_artifact_name: $mg_artifact_name
      pwd
      cp ../README.txt .
      zip $mg_artifact_name README.txt hello
      ls -l $PWD/$mg_artifact_name
  - cmd: |
      msbuild cd_deluxe_vs2015.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - appveyor PushArtifact $mg_artifact_name -DeploymentName cdd_artifact

# failed experiments
    # echo mg_appveyor_build_version_1a: $mg_appveyor_build_version_1a
    # echo mg_appveyor_build_version_1b: $mg_appveyor_build_version_1b
    # echo mg_appveyor_build_version_2a: $mg_appveyor_build_version_2a
    # echo mg_appveyor_build_version_2b: $mg_appveyor_build_version_2b
    # echo mg_appveyor_build_version_3a: $mg_appveyor_build_version_3a
    # echo mg_appveyor_build_version_3b: $mg_appveyor_build_version_3b
    # echo mg_appveyor_build_version_4a: $mg_appveyor_build_version_4a
    # echo mg_appveyor_build_version_5a: $mg_appveyor_build_version_5a
    # echo mg_appveyor_build_version_5b: $mg_appveyor_build_version_5b


# before_deploy:
# # after_build:
# # before_package:
#   - sh: |
#       echo MG before_deploy...
#       echo mg_appveyor_build_version_4b: $mg_appveyor_build_version_4b
#       echo xx echo 1 mg_artifact_name: $mg_artifact_name
#       pwd
#       cp ../README.txt .
#       zip $mg_artifact_name README.txt hello
#       ls -l $PWD/$mg_artifact_name
#   - appveyor PushArtifact $mg_artifact_name -DeploymentName cdd_artifact

# artifacts:
#   - path: build/$mg_artifact_name
#     name: cdd_artifact

deploy:
  - provider: GitHub
    description: 'MG sandbox deploy'
    # artifact: /build\/.*\.zip/
    # artifact: $mg_artifact_name
    artifact: cdd_artifact
    force_update: true
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: 2agopPPVSs1AmZL7j9rh7Sr1msI3hKGjAkuTezGgEgsCvoaWTDdpp0zUl37McW6d
    on:
      branch: master

# vim:sw=2:ts=2:et
