image:
- Ubuntu1804
# - Visual Studio 2015

configuration: Release

environment:
  artifact_name: cdd-v{appveyor_build_version}.zip

# build:
#   project: CMakeLists.txt

build_script:
  sh: |
    mkdir build
    cd build
    cmake --version
    cmake ..
    cmake --build .
  cmd: |
    msbuild cd_deluxe_vs2015.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - echo 'MG preparing artifacts...'
  - echo "xx echo artifact_name: {artifact_name}"
  - pwd
  - zip "{artifact_name} ../README.txt hello"
  - appveyor "PushArtifact {artifact_name}"

# artifacts:
#   - path: Release
#     name: 'MG sandbox artifact'

deploy:
  description: 'MG sandbox deploy'
  provider: GitHub
  auth_token:
    secure: 2agopPPVSs1AmZL7j9rh7Sr1msI3hKGjAkuTezGgEgsCvoaWTDdpp0zUl37McW6d

# vim:sw=2:ts=2:et
